### ISSUE TITLE
Bug in playing cards when board is full (CoreAI)

### ISSUE THREAD

**Issue by tehqin** [HearthSim/SabberStone#165]
I've been working on training a neural network as a scoring function for CoreAI (in place of the heuristics available). Unfortunately, OptionNode is generating moves that try to play a card when the board is full.

Here is the stack track of where the sim crashes when I play games for training:
Unhandled Exception: SabberStoneCore.Exceptions.ZoneException: Can't move 'Silverback Patriarch[27]' to [ZONE PLAY 'Player']. The Zone is full.
   at SabberStoneCore.Model.Zones.LimitedZone`1.MoveTo(T entity, Int32 zonePosition) in /home/tehqin/Projects/HearthStone/SabberStone/SabberStoneCore/src/Model/Zones/Zone.cs:line 319
   at SabberStoneCore.Model.Zones.LimitedZone`1.Add(T entity, Int32 zonePosition) in /home/tehqin/Projects/HearthStone/SabberStone/SabberStoneCore/src/Model/Zones/Zone.cs:line 306
   at SabberStoneCore.Model.Zones.PositioningZone`1.Add(T entity, Int32 zonePosition) in /home/tehqin/Projects/HearthStone/SabberStone/SabberStoneCore/src/Model/Zones/Zone.cs:line 489
   at SabberStoneCore.Model.Zones.BoardZone.Add(Minion entity, Int32 zonePosition) in /home/tehqin/Projects/HearthStone/SabberStone/SabberStoneCore/src/Model/Zones/BoardZone.cs:line 46
   at SabberStoneCore.Actions.Generic.<>c.<get_PlayMinion>b__71_0(Controller c, Game game, Minion minion, ICharacter target, Int32 zonePosition, Int32 chooseOne) in /home/tehqin/Projects/HearthStone/SabberStone/SabberStoneCore/src/Actions/PlayCard.cs:line 257
   at SabberStoneCore.Actions.Generic.<>c.<get_PlayCardBlock>b__63_0(Controller c, IPlayable source, ICharacter target, Int32 zonePosition, Int32 chooseOne, Boolean skipPrePhase) in /home/tehqin/Projects/HearthStone/SabberStone/SabberStoneCore/src/Actions/PlayCard.cs:line 79
   at SabberStoneCore.Actions.Generic.PlayCard(Controller c, IPlayable source, ICharacter target, Int32 zonePosition, Int32 chooseOne, Boolean skipPrePhase) in /home/tehqin/Projects/HearthStone/SabberStone/SabberStoneCore/src/Actions/PlayCard.cs:line 28
   at SabberStoneCore.Model.Game.Process(PlayerTask gameTask) in /home/tehqin/Projects/HearthStone/SabberStone/SabberStoneCore/src/Model/Game.cs:line 476
   at DeckEvaluator.Evaluation.GameEvaluator.PlayGame() in /home/tehqin/Projects/HearthStone/EvoStone/DeckEvaluator/src/Evaluation/GameEvaluator.cs:line 152
   at DeckEvaluator.Evaluation.GameDispatcher.runGame(Int32 gameId, GameEvaluator ev) in /home/tehqin/Projects/HearthStone/EvoStone/DeckEvaluator/src/Evaluation/GameDispatcher.cs:line 72
   at DeckEvaluator.Evaluation.GameDispatcher.Run() in /home/tehqin/Projects/HearthStone/EvoStone/DeckEvaluator/src/Evaluation/GameDispatcher.cs:line 121
   at DeckEvaluator.Program.Main(String[] args) in /home/tehqin/Projects/HearthStone/EvoStone/DeckEvaluator/src/Program.cs:line 117
/opt/gridengine/default/spool/sge_execd/node296/job_scripts/2051164: line 27: 10201 Aborted                 (core dumped) dotnet bin/DeckEvaluator.dll $SGE_TASK_ID

**Comment by rnilva** [comment]
Hello! thank you for your report. Are you using the latest version of SabberStone?

**Comment by tehqin** [comment]
I was using a version pulled from the repository about 2 weeks ago. I just tried to pull from the repository, but now SabberStone won't compile:

Build FAILED.

src/CardSets/Standard/TrollCardsGen.cs(824,16,824,42): error CS0618: 'AdaptiveCostEffectObsolete' is obsolete: 'Not used any more'
src/CardSets/Standard/TrollCardsGen.cs(1101,16,1101,42): error CS0618: 'AdaptiveCostEffectObsolete' is obsolete: 'Not used any more'
src/CardSets/LootapaloozaCardsGen.cs(2789,16,2789,42): error CS0618: 'AdaptiveCostEffectObsolete' is obsolete: 'Not used any more'
src/CardSets/IcecrownCardsGen.cs(2906,16,2906,42): error CS0618: 'AdaptiveCostEffectObsolete' is obsolete: 'Not used any more'
    0 Warning(s)
    4 Error(s)

**Comment by tehqin** [comment]
I went ahead and commented out the failing cards since I'm not using them and the bug still persists. Is there any logging information you would like to have printed to make it easier to replicate the bug?

Other details that may be helpful:
- deck list I'm using: ["Arcane Shot", "Arcane Shot", "Stonetusk Boar",
   "Stonetusk Boar", "Timber Wolf", "Timber Wolf", "Tracking",
   "Tracking", "Bloodfen Raptor", "Bloodfen Raptor", "River Crocolisk",
   "River Crocolisk", "Ironforge Rifleman", "Ironforge Rifleman",
   "Raid Leader", "Raid Leader", "Razorfen Hunter", "Razorfen Hunter",
   "Silverback Patriarch", "Silverback Patriarch", "Houndmaster",
   "Houndmaster", "Multi-Shot", "Multi-Shot", "Oasis Snapjaw",
   "Oasis Snapjaw", "Stormpike Commando", "Stormpike Commando",
   "Core Hound", "Core Hound"]
- I'm training again similar basic only starter decks for hunter, paladin, and warlock using the provided aggro and control strategies.

**Comment by winnowerhs** [comment]
If you're getting errors from Obsolete, you can try commenting the Obsolete tag at https://github.com/HearthSim/SabberStone/blob/master/SabberStoneCore/src/Auras/AdaptiveCostEffectObsolete.cs#L18

It seems like our version of .Net is treating that tag differently, shouldn't cause errors.

Branching from commit 362e642c6280c488f5883c3eb09a193036845b7d (https://github.com/HearthSim/SabberStone/commit/362e642c6280c488f5883c3eb09a193036845b7d) might be a more stable branch.

**Comment by tehqin** [comment]
@winnowerhs I just tested on 362e642. The code compiles but the bug persists.

**Comment by rnilva** [comment]
@tehqin I guess this problem happens because your code allows options that created in some games to the other games. Such that, an option generated by a controller of a game 'A', where its board is not full, and your system applies the option to another game 'B' where the corresponding board is full.

Try this: first, try Controller.GetOptions(false); to generate options. Then write if clause for Game.Process(option). This will detect any illegal options before they are processed.

**Comment by tehqin** [comment]
@rnilva I'm a bit confused about this suggested fix. My game evaluator is adapted from:
https://github.com/HearthSim/SabberStone/blob/master/core-extensions/SabberStoneCoreAi/src/Program.cs

How would you modify "FullGame()"? How would the if clause detect the option is illegal before trying to execute it? My guess for what you mean is before line 265 generate options again for the current game state and compare them with the current PlayerTask and make sure that option matches. Is this correct? If so, how do you compare player tasks?

**Comment by rnilva** [comment]
@tehqin Sorry for the ambiguous expression. I mean this:
```csharp
// OptionsNode.cs line 97
List<PlayerTask> options = _game.ControllerById(_playerId).Options(false);
...
// FullGame()
if (!game.Process(task))
{
    // Process failed
}
```

If failure is detected, I can confirm that this problem is caused by the mismatch of Game and PlayerTask.
In your case, it means CoreAI is the actual problem. Maybe I can fix that when it is confirmed. (I am not the author of the system.)

**Comment by tehqin** [comment]
@rnilva I ran your test and the if statement triggers. The problem is what you thought. Thank you for your help! Is there an easy work around in the meantime?

**Comment by rnilva** [comment]
@tehqin I tried 'FullGame()' with the deck but I could not possible to get the ZoneException. However, I think the most possible cause of the problem is stochastic actions. To elaborate, basically each solution from 'OptionNode.GetSolutions()' contains consecutive `PlayerTask`s. This would not be an issue when all actions are deterministic so that any previously processed actions drive the game state in the same way in the internal game states of the corresponding `OptionNode`s. However, if action is stochastic, i.e., it can have multiple outcomes, following actions in the action sequence in a solution can be invalid.
So maybe the easiest way of fixing the problem is just recalculating solutions always when a stochastic action is processed. Then how? fortunately, there is an event `Game.RandomHappendEvent', which fires signal when some random thing happens during processing.
```csharp
// in FullGame()
bool randomHappened = false;
void RandomHappened(object sender, bool value) // Local function for event subscription
{
    randomHappened = value;
}
...
game.Process(task);
if (game.CurrentPlayer.Choice != null || randomHappened)
{
    Console.WriteLine("* Recalculating ....");
    randomHappened = false;
    break;
}
...
```
I just have realised that implementation of `RandomHappenedEvent` is awful and inconvenient 😞

**Comment by tehqin** [comment]
@rnilva Sorry for the long delay. I couldn't work on this project again until now. Your fix prevents the crash in random actions and I'm using the fix for my project. Thank you for the help. :)

**Comment by rnilva** [comment]
@tehqin Good to hear that!
